### ISSUE TITLE
Autonomous

### ISSUE THREAD

**Issue by open-sourceress** [FRC4131/RecycleRush2015#2]
Make autonomous read values from the Launchpad, and act accordingly.

**Comment by Naoki95957** [comment]
Is the autonomous going to be done in straight line movement or are we going to utilize strafing/gradual-turns? Straight line movement will be quick and easy to produce, however slower than utilizing strafing and gradual-turning

**Comment by open-sourceress** [comment]
We will definitely use strafing. An example implementation would be to get our current coordinates from the FPS, subtract the target coordinates from the current coordinates, and feed that to `mecanumDrive_Cartesian()` to drive in a straight line towards the target.

**Comment by open-sourceress** [comment]
An alternative, more difficult implementation would be to pass in a `Point[]`, where `Point` is a wrapper for an x- and y-coordinate on the field. The robot would find the smoothest path between each of the points, then drive along that path to get where it needs to go.

**Comment by Naoki95957** [comment]
XD um, I did it by accident but, you can assign ppl and un-assign ppl...

**Comment by Naoki95957** [comment]
I'm thinking I'll delete the offlineTesting repo. It was based on the absolute coord system which is now scrapped.

**Comment by open-sourceress** [comment]
Leave it. It'll be good to have if we go back to absolute coordinates.
