### ISSUE TITLE
Accelerometer

### ISSUE THREAD

**Issue by open-sourceress** [FRC4131/RecycleRush2015#6]
We have an ADXL345 accelerometer hooked up over SPI. Using SPI allows us to configure many things on the board, including interrupts. Configure everything we need on the accelerometer and read when an interrupt is tripped (`DigitalInput`).

**Comment by neeshkotov** [comment]
ok what do we need on the accelerometer

2015-02-02 18:31 GMT-08:00 endreman0 notifications@github.com:

**Comment by open-sourceress** [comment]
You need to create a `new SPI(SPI.Port.kOnboardCS0)`, then create a transaction. Mr. Fitzsimons figured out what we need to send, so email him on that part. Basically, we're going to configure it to send out a signal when the robot's acceleration changes by ~1g and goes back down again really quickly.

**Comment by neeshkotov** [comment]
k

2015-02-03 17:02 GMT-08:00 endreman0 notifications@github.com:

**Comment by open-sourceress** [comment]
Page 23 and 24 of [this document](http://www.analog.com/media/en/technical-documentation/data-sheets/ADXL345.pdf) show what all of the keys mean. This should help with finding what values should be sent
